<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>1d7fc8c9-6a26-4b9b-b969-c1a5358ef1bb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Oppdragsportalen.Api.Tests.Integration" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Oppdragsportalen.ServiceDefaults\Oppdragsportalen.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
  </ItemGroup>

</Project>
