name: Oppdragsportalen Api CI

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/**"
  pull_request:
    branches: ["main"]
    paths:
      - "Application/Oppdragsportalen.Api/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore Application/Oppdragsportalen.sln

      - name: Build
        run: dotnet build Application/Oppdragsportalen.sln --no-restore

      - name: Test
        run: dotnet test Application/Oppdragsportalen.Api.Tests.Integration/Oppdragsportalen.Api.Tests.Integration.csproj --no-build --verbosity normal
